package org.personal.mason.domain;

import java.util.ArrayList;
import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * ProductCategory generated by hbm2java
 */
@Document
public class ProductCategory {
@Id
private String id;
private boolean root;
private String categoryName;
private String description;
@DBRef
private List<ProductCategory> productCategories = new ArrayList<>();

public boolean isRoot() {
	return root;
}

public void setRoot(boolean root) {
	this.root = root;
}

public String getCategoryName() {
	return categoryName;
}

public void setCategoryName(String categoryName) {
	this.categoryName = categoryName;
}

public String getDescription() {
	return description;
}

public void setDescription(String description) {
	this.description = description;
}

public List<ProductCategory> getProductCategories() {
	return productCategories;
}

public void setProductCategories(List<ProductCategory> productCategories) {
	this.productCategories = productCategories;
}

public String getId() {
	return id;
}

public void setId(String id) {
	if (id.isEmpty()) {
		this.id = null;
	} else {
		this.id = id;
	}
}
}
