package org.personal.mason.domain;

import java.util.List;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * ProductCategory generated by hbm2java
 */
@Document
public class ProductCategory {
@Id
private String id;
private String categoryName;
private String description;
@DBRef
private List<ProductCategory> productCategories;

public String getCategoryName() {
	return categoryName;
}

public void ListCategoryName(String categoryName) {
	this.categoryName = categoryName;
}

public String getDescription() {
	return description;
}

public void ListDescription(String description) {
	this.description = description;
}

public List<ProductCategory> getProductCategories() {
	return productCategories;
}

public void setProductCategories(List<ProductCategory> productCategories) {
	this.productCategories = productCategories;
}

public String getId() {
	return id;
}

}
