package org.personal.mason.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

// Generated Oct 25, 2012 9:29:03 PM by Hibernate Tools 3.4.0.CR1
/**
 * User generated by hbm2java
 */
@Document
public class User {

@Id
private String id;
@Indexed(unique = true)
private String email;
private String name;
private String password;

public String getEmail() {
	return email;
}

public void setEmail(String email) {
	this.email = email;
}

public String getName() {
	return name;
}

public void setName(String name) {
	this.name = name;
}

public String getPassword() {
	return password;
}

public void setPassword(String password) {
	this.password = password;
}

public String getId() {
	return id;
}

}
