package org.personal.mason.domain;

// Generated Oct 25, 2012 9:29:03 PM by Hibernate Tools 3.4.0.CR1


/**
 * Label generated by hbm2java
 */
public class Label {
private String id;
private String labelName;

public String getLabelName() {
	return labelName;
}

public void setLabelName(String labelName) {
	this.labelName = labelName;
}

public String getId() {
	return id;
}

public void setId(String id) {
	if (id.isEmpty()) {
		this.id = null;
	} else {
		this.id = id;
	}
}
}
