package org.personal.mason.job.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompanyLabel generated by hbm2java
 */
@Entity
@Table(name = "company_label")
public class CompanyLabel implements java.io.Serializable {
private static final long serialVersionUID = 6747408838280909409L;
private long id;
private Label label;
private Company company;

public CompanyLabel() {
}

public CompanyLabel(long id, Label label, Company company) {
	this.id = id;
	this.label = label;
	this.company = company;
}

@Id
@Column(name = "id", unique = true, nullable = false)
public long getId() {
	return this.id;
}

public void setId(long id) {
	this.id = id;
}

@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "label_id", nullable = false)
public Label getLabel() {
	return this.label;
}

public void setLabel(Label label) {
	this.label = label;
}

@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "company_id", nullable = false)
public Company getCompany() {
	return this.company;
}

public void setCompany(Company company) {
	this.company = company;
}

}
