package org.personal.mason.job.domain;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InterviewMaterial generated by hbm2java
 */
@Entity
@Table(name = "interview_material")
public class InterviewMaterial implements java.io.Serializable {
private static final long serialVersionUID = -7415624374762348973L;
private Long id;
private int weight;
private String question;
private String answer;
private Date addDate;
private String type;

public InterviewMaterial() {
}

public InterviewMaterial(int weight, String question) {
	this.weight = weight;
	this.question = question;
}

public InterviewMaterial(int weight, String question, String answer, Date addDate, String type) {
	this.weight = weight;
	this.question = question;
	this.answer = answer;
	this.addDate = addDate;
	this.type = type;
}

@Id
@GeneratedValue(strategy = IDENTITY)
@Column(name = "id", unique = true, nullable = false)
public Long getId() {
	return this.id;
}

public void setId(Long id) {
	this.id = id;
}

@Column(name = "weight", nullable = false)
public int getWeight() {
	return this.weight;
}

public void setWeight(int weight) {
	this.weight = weight;
}

@Column(name = "question", nullable = false, length = 1000)
public String getQuestion() {
	return this.question;
}

public void setQuestion(String question) {
	this.question = question;
}

@Column(name = "answer", length = 1000)
public String getAnswer() {
	return this.answer;
}

public void setAnswer(String answer) {
	this.answer = answer;
}

@Temporal(TemporalType.TIMESTAMP)
@Column(name = "add_date", length = 19)
public Date getAddDate() {
	return this.addDate;
}

public void setAddDate(Date addDate) {
	this.addDate = addDate;
}

@Column(name = "type", length = 20)
public String getType() {
	return this.type;
}

public void setType(String type) {
	this.type = type;
}

}
