package org.personal.mason.job.domain;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name = "job")
public class Job implements java.io.Serializable {
private static final long serialVersionUID = 7210678907540914336L;
private Long id;
private Company company;
private String jobTitle;
private Date publishDate;
private String requiredTech;
private String content;

public Job() {
}

public Job(Company company, String jobTitle) {
	this.company = company;
	this.jobTitle = jobTitle;
}

public Job(Company company, String jobTitle, Date publishDate, String requiredTech, String content) {
	this.company = company;
	this.jobTitle = jobTitle;
	this.publishDate = publishDate;
	this.requiredTech = requiredTech;
	this.content = content;
}

@Id
@GeneratedValue(strategy = IDENTITY)
@Column(name = "id", unique = true, nullable = false)
public Long getId() {
	return this.id;
}

public void setId(Long id) {
	this.id = id;
}

@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "company_id", nullable = false)
public Company getCompany() {
	return this.company;
}

public void setCompany(Company company) {
	this.company = company;
}

@Column(name = "job_title", nullable = false, length = 100)
public String getJobTitle() {
	return this.jobTitle;
}

public void setJobTitle(String jobTitle) {
	this.jobTitle = jobTitle;
}

@Temporal(TemporalType.TIMESTAMP)
@Column(name = "publish_date", length = 19)
public Date getPublishDate() {
	return this.publishDate;
}

public void setPublishDate(Date publishDate) {
	this.publishDate = publishDate;
}

@Column(name = "required_tech")
public String getRequiredTech() {
	return this.requiredTech;
}

public void setRequiredTech(String requiredTech) {
	this.requiredTech = requiredTech;
}

@Column(name = "content", columnDefinition="TEXT")
public String getContent() {
	return this.content;
}

public void setContent(String content) {
	this.content = content;
}

}
