package org.personal.mason.job.domain;

// Generated Oct 25, 2012 9:29:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Label generated by hbm2java
 */
@Entity
@Table(name = "label")
public class Label implements java.io.Serializable {
private static final long serialVersionUID = -5379590302180459359L;
private Long id;
private String labelName;
private Set<Company> companies = new HashSet<Company>(0);

public Label() {
}

public Label(String labelName) {
	this.labelName = labelName;
}

public Label(String labelName, Set<Company> companies) {
	this.labelName = labelName;
	this.companies = companies;
}

@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
@Column(name = "id", unique = true, nullable = false)
public Long getId() {
	return this.id;
}

public void setId(Long id) {
	this.id = id;
}

@Column(name = "label_name", nullable = false, length = 50)
public String getLabelName() {
	return this.labelName;
}

public void setLabelName(String labelName) {
	this.labelName = labelName;
}

@JsonIgnore
@ManyToMany(fetch = FetchType.EAGER, mappedBy="labels")
public Set<Company> getCompanies() {
	return companies;
}

public void setCompanies(Set<Company> companies) {
	this.companies = companies;
}

}
