package org.personal.mason.job.domain;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.search.annotations.Field;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "news")
public class News implements java.io.Serializable {
private static final long serialVersionUID = -6952425625027461646L;
private Long id;
private Company company;
private String title;
private Date date;
private String content;
private String description;

public News() {
}

public News(Company company, String title, Date date, String content) {
	this.company = company;
	this.title = title;
	this.date = date;
	this.content = content;
}

public News(Company company, String title, Date date, String content, String description) {
	this.company = company;
	this.title = title;
	this.date = date;
	this.content = content;
	this.description = description;
}

@Id
@GeneratedValue(strategy = IDENTITY)
@Column(name = "id", unique = true, nullable = false)
public Long getId() {
	return this.id;
}

public void setId(Long id) {
	this.id = id;
}

@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "company_id", nullable = false)
public Company getCompany() {
	return this.company;
}

public void setCompany(Company company) {
	this.company = company;
}

@Field
@Column(name = "title", nullable = false)
public String getTitle() {
	return this.title;
}

public void setTitle(String title) {
	this.title = title;
}

@Temporal(TemporalType.TIMESTAMP)
@Column(name = "date", nullable = false, length = 19)
public Date getDate() {
	return this.date;
}

public void setDate(Date date) {
	this.date = date;
}

@Column(name = "content", nullable = false, columnDefinition="TEXT")
public String getContent() {
	return this.content;
}

public void setContent(String content) {
	this.content = content;
}

@Column(name = "description")
public String getDescription() {
	return this.description;
}

public void setDescription(String description) {
	this.description = description;
}

}
